import { StyleSheet } from 'react-native';
import Utils from '../../Utils'

export default StyleSheet.create({
	body:{
		flex:1,
		backgroundColor:Utils.colorWhite
	},
	header:{
		flex:0.1
	},
	footer:{
		flex:0.1
	},
	container:{
		width:'95%',
		alignSelf:'center',
		marginTop:10
	},
	shadow:{
			shadowColor: Utils.colorPrimary,
			shadowOffset: {
				width: 0,
				height: 9,
			},
			shadowOpacity: 1,
			shadowRadius: 11.95,
			elevation: 10,
	},
	textLabel:{
		color:Utils.colorBlack,
		flex:0.5
	},
	textValue:{
		color:Utils.colorBlack,
		flex:0.5,
		fontSize:Utils.subHeadSize
	},
	textLabelCheck:{
		color:Utils.colorGray
	},
	textValueInput:{
		borderWidth:1,
		borderRadius:5,
		borderColor:Utils.colorGray,
		height:45,
		flex:0.5,
	},
	textValueInputError:{
		borderWidth:2,
		borderRadius:5,
		borderColor:Utils.colorRed,
		height:45,
		flex:0.5,
	},
	pickerView:{
		alignSelf:'center',
		borderRadius:5,
		borderWidth:1,
		borderColor:Utils.colorGray,
		marginTop:10,
		flex:0.5,
		height:40,
		justifyContent:'center',
	},
	pickerViewError:{
		alignSelf:'center',
		borderRadius:5,
		borderWidth:2,
		borderColor:Utils.colorRed,
		marginTop:10,
		flex:0.5,
		height:40,
		justifyContent:'center',
	},
	countryView:{
		alignSelf:'center',
		borderRadius:5,
		borderWidth:1,
		borderColor:Utils.colorGray,
		marginTop:10,
	},
	countryViewError:{
		alignSelf:'center',
		borderRadius:5,
		borderWidth:2,
		borderColor:Utils.colorRed,
		marginTop:10,
	},
	fileView:{
		marginVertical:10, 
		flexDirection:'row',
		borderRadius:5,
		borderWidth:1,
		borderColor:Utils.colorGray,
		height:45,
		width:'100%',
		flex:1,
		paddingLeft:10,
		paddingRight:30,
		alignItems:'center',
		},
	fileViewError:{
		marginVertical:10, 
		flexDirection:'row',
		borderRadius:5,
		borderWidth:2,
		borderColor:Utils.colorRed,
		height:45,
		width:'100%',
		flex:1,
		paddingLeft:10,
		paddingRight:30,
		alignItems:'center',
	},
	picker:{
		marginTop:-7
	},
	rightIcon:{
		position:'absolute',
		right:15,
		top:10,
		fontSize:24
	},
	textSelectPhoto:{
		
	},
	submitButton:{
		borderRadius:5,
		backgroundColor:Utils.colorGreen,
		height:45,
		textAlign:'center',
		width:'90%',
		alignSelf:'center',
		marginVertical:20,
		alignItems:'center',
		justifyContent:'center'
	},
	dialogueContainer:{
		width:320,
		alignSelf:'center',
		alignItems: 'center',
		backgroundColor : Utils.colorWhite, 
		height: 300,
		borderWidth: 1,
		borderColor:Utils.colorPrimary,
		borderRadius:17,
	},
	close:{
		position:'absolute',
		right:15,
		top:15,
		fontSize:Utils.headSize+5
	},
	phoneVeriLine:{
		fontWeight:'bold', 
		fontSize:Utils.headSize,
		marginTop:15,
		alignSelf:'flex-start',
		marginLeft:20
	},
	otpBox:{
		height:40,
		borderWidth:1,
		borderColor:Utils.colorGray,
		borderRadius:5,
		marginHorizontal:5,
		textAlign:'center'
	},
	phoneVeriButton:{
		borderRadius:5,
		backgroundColor:Utils.colorGreen,
		height:45,
		textAlign:'center',
		width:'40%',
		alignSelf:'center',
		marginVertical:30,
		marginHorizontal:5,
		alignItems:'center',
		justifyContent:'center'
	},
	placeholder:{
		width:'100%', 
		paddingHorizontal:5,
		color:Utils.colorGray
	},
	dropItemSelected:{
		width:'100%', 
		paddingHorizontal:5,
		color:Utils.colorBlack
	},
	dropIcon:{
		position:'absolute', 
		right:15,
		fontSize:Utils.headSize,
		color:Utils.colorDarkGray
	}

})