import { StyleSheet } from 'react-native';
import Utils from '../Utils'

export default StyleSheet.create({
	body:{
		flex:1,
		backgroundColor:Utils.colorWhite
	},
	header:{
		flex:0.1
	},
	footer:{
		flex:0.1
	},
	container:{
		width:'100%',
	},
	heading:{
		backgroundColor:Utils.colorDarkBlue,
		color:Utils.colorWhite,
		fontSize:Utils.headSize,
		width:'95%',
		textAlign:'center',
		alignSelf:'center'
	},
	radioView:{
		width:'100%',
		flexDirection:'row',
		marginTop:20,
		marginLeft:20,
		alignItems:'center',
	},
	radioText:{
		marginTop:-5,
		flex:0.4,
	},
	itemlebal:{
		color:Utils.colorDarkGray
	},
	boldText:{
		fontWeight:'bold',
		color:Utils.colorBlack
	},
	countryView:{
		alignSelf:'center',
		borderRadius:5,
		borderWidth:1,
		borderColor:Utils.colorGray,
		flexDirection:'row',
		alignItems:'center'
	},
	countryViewError:{
		alignSelf:'center',
		borderRadius:5,
		borderWidth:2,
		borderColor:Utils.colorRed,
		flexDirection:'row',
		alignItems:'center'
	},
	pickerView:{
		height:42,
		flex:0.5,
		marginTop:10,
		backgroundColor:Utils.colorWhite,
		borderRadius:5,
		borderWidth:1,
		borderColor:Utils.colorGray,
		justifyContent:'center'
	},
	pickerViewError:{
		height:42,
		flex:0.5,
		marginTop:10,
		backgroundColor:Utils.colorWhite,
		borderRadius:5,
		borderWidth:1,
		borderColor:Utils.colorRed,
		justifyContent:'center'
	},
	securityView:{
		marginLeft:20,
		marginTop:20,
	},
	checkRow:{
		flexDirection:'row',
		alignItems:'center',
		marginTop:10
	},
	inputText:{
		borderRadius:5,
		borderWidth:1,
		borderColor:Utils.colorGray,
		height:40,	
		paddingHorizontal:10
	},
	inputTextError:{
		flex:0.5,
		borderRadius:5,
		borderWidth:2,
		borderColor:Utils.colorRed,
		height:40,	
		paddingHorizontal:10
	},
	detailsLabelText:{
		flex:0.5
	},
	inputTextDetails:{
		flex:0.40,
		borderRadius:5,
		borderWidth:1,
		borderColor:Utils.colorGray,
		height:40,	
		alignSelf:'flex-end',
		justifyContent:'center',
		paddingHorizontal:10
	},
	detailsInputArea:{
		minHeight:100,
		marginHorizontal:20,
		borderRadius:5,
		borderWidth:1,
		borderColor:Utils.colorGray,
		marginTop:10,
		paddingHorizontal:10,
		textAlignVertical:'top'
	},
	detailsInputAreaError:{
		minHeight:100,
		marginHorizontal:20,
		borderRadius:5,
		borderWidth:2,
		borderColor:Utils.colorRed,
		marginTop:10,
		paddingHorizontal:10,
		textAlignVertical:'top'
	},
	copyIcon:{
		color:Utils.colorBlack,
		alignSelf:'flex-end',
		marginRight:10,
		fontSize:20,
		marginTop:-30
	},
	bitAddress:{
		textAlign:'center'
	},
	nextButton:{
		backgroundColor:Utils.colorDarkBlue,
		width:'21%',
		height:40,
		alignSelf:'center',
		marginRight:35,
		textAlign:'center',
		marginVertical:15,
		borderRadius:5,
		alignItems:'center',
		justifyContent:'center'
	},
	submitBotton:{
		backgroundColor:Utils.colorGreen,
		height:40,
		alignSelf:'center',
		textAlign:'center',
		marginVertical:20,
		borderRadius:5,
		alignItems:'center',
		justifyContent:'center',
		paddingHorizontal:20
	},
	tagBox:{
		borderWidth:1,
		borderColor:Utils.colorGray,
		padding:5,
		width:'45%',
		marginVertical:5,
		marginHorizontal:20,
		flexDirection:'row',
		borderRadius:5,
		borderStyle:'dotted'
	},
	cross:{
		fontSize:Utils.headSize,
		color:Utils.colorBlack,
		position:'absolute',
		right:10,
		top:5
	},
	placeholder:{
		width:'100%', 
		paddingHorizontal:5,
		color:Utils.colorGray
	},
	dropItem:{
		width:'95%',
		paddingRight:5,
		color:Utils.colorBlack,
		fontSize:Utils.textSize,
		marginTop:2,
	},
	dropIcon:{
		position:'absolute', 
		right:15,
		top:7,
		fontSize:Utils.headSize,
		color:Utils.colorDarkGray
	},
	ok:{
		alignSelf:'center', 
		marginVertical:10,
		backgroundColor:Utils.colorGreen,
		width:'50%',
		alignItems:'center',
		justifyContent:'center',
		height:40,
		borderRadius:20,
		flex:0.07
	},
	dialogue:{
		alignSelf:'center',
		justifyContent:'center',
		backgroundColor:'#00000088',
		width:'100%',
		height:'100%',
		alignItems:'center',
	},
	dialogueContainer:{
		height:'99%',
		width:'98%',
		backgroundColor : Utils.colorWhite,
		borderWidth: 1,
		borderColor:Utils.colorGreen,
		borderRadius:17,
	},


})